// This file is part of the Prowl Game Engine
// Licensed under the MIT License. See the LICENSE file in the project root for details.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Prowl.Slang.COMApi;

[Generator]
public sealed class ComProxyGenerator : IIncrementalGenerator
{
    private const string UuidAttributeMetadataName = "Prowl.Slang.Native.UUIDAttribute";
    private const string SlangResultType = "global::Prowl.Slang.Native.SlangResult";



    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<INamedTypeSymbol> interfaces = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                UuidAttributeMetadataName,
                static (node, _) => node is InterfaceDeclarationSyntax,
                static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol)
            .Where(static symbol => symbol.Name != "IUnknown");

        context.RegisterSourceOutput(interfaces, static (spc, iface) => Generate(spc, iface));
    }


    private static void Generate(SourceProductionContext spc, INamedTypeSymbol iface)
    {
        string ifaceName = iface.Name;
        string ifaceDisplay = Display(iface);
        string nativeClassName = "Native" + ifaceName.Substring(1);
        string thunksStructName = ifaceName.Substring(1) + "Thunks";
        string ns = iface.ContainingNamespace.ToDisplayString();

        List<(IMethodSymbol Method, int Slot)> methods = GetAllMethodsWithSlots(iface);
        List<string> guidLiterals = GetGuidChain(iface).Select(GetUuidLiteral).ToList();

        StringBuilder sb = new();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine();
        sb.Append("namespace ").Append(ns).AppendLine(";");
        sb.AppendLine();

        EmitNativeProxy(sb, nativeClassName, ifaceDisplay, methods);
        sb.AppendLine();
        EmitManagedThunks(sb, thunksStructName, ifaceDisplay, methods, guidLiterals);

        spc.AddSource($"{ifaceName}.g.cs", sb.ToString());
    }


    private static void EmitNativeProxy(StringBuilder sb, string className, string ifaceDisplay, List<(IMethodSymbol Method, int Slot)> methods)
    {
        sb.Append("internal sealed unsafe class ").Append(className).Append(" : global::Prowl.Slang.Native.NativeComProxy, ").AppendLine(ifaceDisplay);
        sb.AppendLine("{");

        sb.Append("    public ").Append(className).Append('(').Append(ifaceDisplay).AppendLine("* ptr, bool trackReferences = true) : base(ptr, trackReferences) { }");

        foreach ((IMethodSymbol method, int slot) in methods)
        {
            string returnType = Display(method.ReturnType);
            List<(RefKind RefKind, string Type, string Name)> parameters = GetParams(method);

            string paramList = string.Join(", ", parameters.Select(p => $"{RefKindPrefix(p.RefKind)}{p.Type} {p.Name}"));
            string delegateParams = string.Join(", ", new[] { "void*" }.Concat(parameters.Select(p => $"{RefKindPrefix(p.RefKind)}{p.Type}")).Append(returnType));
            string callArgs = string.Join(", ", new[] { "_ptr" }.Concat(parameters.Select(p => $"{RefKindPrefix(p.RefKind)}{p.Name}")));

            sb.AppendLine();
            sb.Append("    public ").Append(returnType).Append(' ').Append(method.Name).Append('(').Append(paramList).AppendLine(")");
            sb.AppendLine("    {");
            sb.Append("        var fn = (delegate* unmanaged[Cdecl]<").Append(delegateParams).Append(">)VTable[").Append(slot).AppendLine("];");

            if (method.ReturnsVoid)
                sb.Append("        fn(").Append(callArgs).AppendLine(");");
            else
                sb.Append("        return fn(").Append(callArgs).AppendLine(");");

            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
    }


    private static void EmitManagedThunks(StringBuilder sb, string structName, string ifaceDisplay, List<(IMethodSymbol Method, int Slot)> methods, List<string> guidLiterals)
    {
        int totalSlots = 3 + methods.Count;

        sb.Append("internal readonly unsafe struct ").Append(structName).Append(" : global::Prowl.Slang.Native.IManagedProxyThunks<").Append(ifaceDisplay).AppendLine(">");
        sb.AppendLine("{");

        sb.Append("    private static readonly Guid[] s_guids = new Guid[] { ").Append(string.Join(", ", guidLiterals)).AppendLine(" };");
        sb.AppendLine();

        sb.Append("    public static int SlotCount => ").Append(totalSlots).AppendLine(";");
        sb.AppendLine();

        sb.AppendLine("    public static void FillVTable(void** vtable)");
        sb.AppendLine("    {");
        sb.Append("        vtable[0] = (void*)(delegate* unmanaged[Cdecl]<global::Prowl.Slang.Native.ProxyVTable*, Guid*, nint*, ").Append(SlangResultType).AppendLine(">)&QueryInterface;");
        sb.AppendLine("        vtable[1] = (void*)(delegate* unmanaged[Cdecl]<global::Prowl.Slang.Native.ProxyVTable*, uint>)&global::Prowl.Slang.Native.ManagedProxyHelpers.AddRef;");
        sb.AppendLine("        vtable[2] = (void*)(delegate* unmanaged[Cdecl]<global::Prowl.Slang.Native.ProxyVTable*, uint>)&global::Prowl.Slang.Native.ManagedProxyHelpers.Release;");

        foreach ((IMethodSymbol method, int slot) in methods)
        {
            string returnType = Display(method.ReturnType);
            List<(RefKind RefKind, string Type, string Name)> parameters = GetParams(method);

            string delegateParams = string.Join(", ", new[] { "global::Prowl.Slang.Native.ProxyVTable*" }.Concat(parameters.Select(ThunkParamType)).Append(returnType));

            sb.Append("        vtable[").Append(slot).Append("] = (void*)(delegate* unmanaged[Cdecl]<").Append(delegateParams).Append(">)&").Append(method.Name).AppendLine(";");
        }

        sb.AppendLine("    }");

        sb.AppendLine();
        sb.AppendLine("    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]");
        sb.Append("    private static ").Append(SlangResultType).AppendLine(" QueryInterface(global::Prowl.Slang.Native.ProxyVTable* self, Guid* uuid, nint* obj)");
        sb.AppendLine("    {");
        sb.AppendLine("        for (int i = 0; i < s_guids.Length; i++)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (s_guids[i] == *uuid)");
        sb.AppendLine("            {");
        sb.AppendLine("                *obj = (nint)self;");
        sb.Append("                return ").Append(SlangResultType).AppendLine(".Ok;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        *obj = 0;");
        sb.Append("        return ").Append(SlangResultType).AppendLine(".NoInterface;");
        sb.AppendLine("    }");

        foreach ((IMethodSymbol method, _) in methods)
        {
            string returnType = Display(method.ReturnType);
            List<(RefKind RefKind, string Type, string Name)> parameters = GetParams(method);

            string paramList = string.Join(", ", new[] { "global::Prowl.Slang.Native.ProxyVTable* self" }.Concat(parameters.Select(p => $"{ThunkParamType(p)} {p.Name}")));
            string callArgs = string.Join(", ", parameters.Select(p => p.RefKind == RefKind.None ? p.Name : $"{RefKindPrefix(p.RefKind)}*{p.Name}"));

            sb.AppendLine();
            sb.AppendLine("    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]");
            sb.Append("    private static ").Append(returnType).Append(' ').Append(method.Name).Append('(').Append(paramList).AppendLine(")");
            sb.AppendLine("    {");
            sb.Append("        var __target = (").Append(ifaceDisplay).Append(")global::Prowl.Slang.Native.ManagedProxyHelpers.GetTarget(self);").AppendLine();

            if (method.ReturnsVoid)
                sb.Append("        __target.").Append(method.Name).Append('(').Append(callArgs).AppendLine(");");
            else
                sb.Append("        return __target.").Append(method.Name).Append('(').Append(callArgs).AppendLine(");");

            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
    }


    private static string ThunkParamType((RefKind RefKind, string Type, string Name) p) => p.RefKind == RefKind.None ? p.Type : $"{p.Type}*";


    private static List<(RefKind RefKind, string Type, string Name)> GetParams(IMethodSymbol method)
    {
        return method.Parameters.Select(p => (p.RefKind, Display(p.Type), p.Name)).ToList();
    }


    private static List<(IMethodSymbol Method, int Slot)> GetAllMethodsWithSlots(INamedTypeSymbol iface)
    {
        List<INamedTypeSymbol> chain = new();
        INamedTypeSymbol? current = iface;

        while (current != null && current.Name != "IUnknown")
        {
            chain.Add(current);
            current = current.Interfaces.FirstOrDefault();
        }

        chain.Reverse();

        List<(IMethodSymbol, int)> result = new();
        int slot = 3;

        foreach (INamedTypeSymbol level in chain)
        {
            foreach (IMethodSymbol method in GetOwnMethods(level))
                result.Add((method, slot++));
        }

        return result;
    }


    private static List<IMethodSymbol> GetOwnMethods(INamedTypeSymbol iface)
    {
        return iface.GetMembers().OfType<IMethodSymbol>().Where(m => m.MethodKind == MethodKind.Ordinary).ToList();
    }


    private static List<INamedTypeSymbol> GetGuidChain(INamedTypeSymbol iface)
    {
        List<INamedTypeSymbol> chain = new();
        INamedTypeSymbol? current = iface;

        while (current != null)
        {
            chain.Add(current);
            current = current.Interfaces.FirstOrDefault();
        }

        return chain;
    }


    private static string GetUuidLiteral(INamedTypeSymbol iface)
    {
        AttributeData attr = iface.GetAttributes().First(a => a.AttributeClass?.ToDisplayString() == UuidAttributeMetadataName);

        ulong[] values = attr.ConstructorArguments.Select(tc => Convert.ToUInt64(tc.Value)).ToArray();

        string a = $"unchecked((int)0x{values[0]:X8}u)";
        string b = $"unchecked((short)0x{values[1]:X4})";
        string c = $"unchecked((short)0x{values[2]:X4})";
        string bytes = string.Join(", ", values.Skip(3).Select(v => $"0x{v:X2}"));

        return $"new global::System.Guid({a}, {b}, {c}, {bytes})";
    }


    private static string RefKindPrefix(RefKind kind) => kind switch
    {
        RefKind.Ref => "ref ",
        RefKind.Out => "out ",
        RefKind.In => "in ",
        _ => "",
    };


    private static string Display(ITypeSymbol type) => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
}
