// <auto-generated> Generated from Quill/Shaders/Canvas.slang by Quill.ShaderGen. Do not edit.
//
// Matrix convention: unlike the GLSL backends, nothing here needs transposing. Slang emits
// mul(M, v) as v * M for HLSL too, but it also emits #pragma pack_matrix(row_major), which
// the GLSL path loses when its uniform block is unpacked. The two cancel out.
Shader "Quill/CanvasShader"
{
    Properties
    {
        texture0 ("Texture", 2D) = "white" {}
        fontTexture ("Font Atlas", 2D) = "white" {}
        backdropTexture ("Backdrop", 2D) = "black" {}
    }
    SubShader
    {
        Tags { "Queue"="Transparent" "IgnoreProjector"="True" "RenderType"="Transparent" }
        LOD 100

        Lighting Off
        Cull Off
        ZWrite On
        ZTest Always
        Blend One OneMinusSrcAlpha  // Quill emits premultiplied colours

        Pass
        {
            Name "QUILL BUILTIN"

            HLSLPROGRAM
            #pragma target 4.5
            #pragma vertex Vertex
            #pragma fragment Fragment
            #pragma pack_matrix(row_major)

            #ifndef __DXC_VERSION_MAJOR
            // warning X3557: loop doesn't seem to do anything, forcing loop to unroll
            #pragma warning(disable : 3557)
            #endif

            #line 9 "Canvas.slang"
            #line 9
            float4x4 projection;
                float2 fragTexCoord_0 : TEXCOORD0;
                float4 fragColor_0 : COLOR0;
                float2 fragPos_0 : TEXCOORD1;
            };

            #line 9
            struct VertexInput_0
            {
                float2 aPosition_0 : POSITION0;
                float2 aTexCoord_0 : TEXCOORD0;
                float4 aColor_0 : COLOR0;
            };

            #line 69
            VertexOutput_0 Vertex(VertexInput_0 input_0)
            {
                VertexOutput_0 output_0;
                output_0.fragTexCoord_0 = input_0.aTexCoord_0;
                output_0.fragColor_0 = input_0.aColor_0;
                output_0.fragPos_0 = input_0.aPosition_0;
                output_0.position_0 = mul(projection, float4(input_0.aPosition_0, 0.0f, 1.0f));
                return output_0;
            }


            #pragma pack_matrix(row_major)

            #ifndef __DXC_VERSION_MAJOR
            // warning X3557: loop doesn't seem to do anything, forcing loop to unroll
            #pragma warning(disable : 3557)
            #endif

            #line 90 "core"
            Texture2D<float4 > fontTexture;

            #line 1094 "hlsl.meta.slang"
            SamplerState sampler_fontTexture;

            #line 1094
            Texture2D<float4 > texture0;

            #line 1094
            SamplerState sampler_texture0;

            #line 1094
            Texture2D<float4 > backdropTexture;

            #line 1094
            SamplerState sampler_backdropTexture;

            #line 11223
            #line 11223
            float4 scissorTransform;
            float2 scissorTranslation;
            float2 scissorExt;
            float4 brushTransform;
            float2 brushTranslation;
            int brushType;
            float4 brushColor1;
            float4 brushColor2;
            float4 brushParams;
            float2 brushParams2;
            float4 textureTransform;
            float2 textureTranslation;
            float2 atlasTexelSize;
            float sdfPxRange;
            float2 viewportSize;
            float backdropBlurAmount;
            int backdropFlipY;
            }

            #line 114
            float scissorMask_0(float2 p_1)
            {

            #line 114
                bool _S1;

                if((scissorExt.x) < 0.0f)
                {

            #line 116
                    _S1 = true;

            #line 116
                }
                else
                {

            #line 116
                    _S1 = (scissorExt.y) < 0.0f;

            #line 116
                }

            #line 116
                if(_S1)
                {

            #line 117
                    return 1.0f;
                }

                float2 smoothEdges_0 = scissorExt - abs(applyTransform_0(scissorTransform, scissorTranslation, p_1));

                return clamp(smoothEdges_0.x, 0.0f, 1.0f) * clamp(smoothEdges_0.y, 0.0f, 1.0f);
            }

            #line 80
            float calculateBrushFactor_0(float2 fragPos_0)
            {
                float2 transformedPoint_0 = applyTransform_0(brushTransform, brushTranslation, fragPos_0);

                if((brushType) == int(1))
                {
                    float2 startPoint_0 = brushParams.xy;

                    float2 line_0 = brushParams.zw - startPoint_0;
                    float lineLength_0 = length(line_0);
                    if(lineLength_0 < 0.00100000004749745f)
                    {

            #line 90
                        return 0.0f;
                    }

            #line 91
                    return clamp(dot(transformedPoint_0 - startPoint_0, line_0) / (lineLength_0 * lineLength_0), 0.0f, 1.0f);
                }
                if((brushType) == int(2))
                {

                    return clamp(smoothstep(brushParams.z, brushParams.w, length(transformedPoint_0 - brushParams.xy)), 0.0f, 1.0f);
                }
                if((brushType) == int(3))
                {
                    float2 center_0 = brushParams.xy;
                    float2 halfSize_0 = brushParams.zw;
                    float radius_0 = brushParams2.x;
                    float feather_0 = brushParams2.y;

            #line 103
                    bool _S2;
                    if((halfSize_0.x) < 0.00100000004749745f)
                    {

            #line 104
                        _S2 = true;

            #line 104
                    }
                    else
                    {

            #line 104
                        _S2 = (halfSize_0.y) < 0.00100000004749745f;

            #line 104
                    }

            #line 104
                    if(_S2)
                    {

            #line 104
                        return 0.0f;
                    }
                    float2 q_0 = abs(transformedPoint_0 - center_0) - (halfSize_0 - (float2)radius_0);

                    return smoothstep(- feather_0 * 0.5f, feather_0 * 0.5f, min(max(q_0.x, q_0.y), 0.0f) + length(max(q_0, (float2)0.0f)) - radius_0);
                }
                return 0.0f;
            }

            #line 128
            float sdfScreenPxRange_0(float2 uv_0)
            {

            #line 138
                float2 range_0 = (float2)sdfPxRange * atlasTexelSize * ((float2)1.0f / (fwidth((uv_0))));
                return max(min(range_0.x, range_0.y), 1.0f);
            }

            #line 16
            struct VertexOutput_0
            {
                float4 position_0 : SV_Position;
                float2 fragTexCoord_0 : TEXCOORD0;
                float4 fragColor_0 : COLOR0;
                float2 fragPos_1 : TEXCOORD1;
            };

            #line 144
            float4 Fragment(VertexOutput_0 input_0) : SV_TARGET
            {
                float mask_0 = scissorMask_0(input_0.fragPos_1);

            #line 146
                float4 _S3 = input_0.fragColor_0;

            #line 146
                float4 color_0;

                if((brushType) > int(0))
                {

            #line 150
                    color_0 = lerp(brushColor1, brushColor2, (float4)calculateBrushFactor_0(input_0.fragPos_1));

            #line 150
                }
                else
                {

            #line 150
                    color_0 = _S3;

            #line 150
                }

            #line 158
                if((input_0.fragTexCoord_0.x) >= 2.0f)
                {
                    float2 uv_1 = input_0.fragTexCoord_0 - (float2)2.0f;
                    ;

                    return color_0 * clamp(sdfScreenPxRange_0(uv_1) * (fontTexture.Sample(sampler_fontTexture, uv_1).x - 0.5f) + 0.5f, 0.0f, 1.0f) * mask_0;
                }

                float edgeAlpha_0 = clamp(input_0.fragTexCoord_0.x, 0.0f, 1.0f);

                float2 _S4 = applyTransform_0(textureTransform, textureTranslation, input_0.fragPos_1);

            #line 171
                ;

            #line 171
                float4 fill_0 = color_0 * texture0.Sample(sampler_texture0, _S4);

                if((backdropBlurAmount) > 0.0f)
                {
                    float2 uv_2 = input_0.fragPos_1 / viewportSize;
                    if((backdropFlipY) == int(1))
                    {

            #line 178
                        uv_2[int(1)] = 1.0f - uv_2.y;

            #line 177
                    }

                    float2 _S5 = uv_2;

            #line 179
                    ;

                    return float4(backdropTexture.Sample(sampler_backdropTexture, _S5).xyz * (1.0f - fill_0.w) + fill_0.xyz, 1.0f) * edgeAlpha_0 * mask_0;
                }

                return fill_0 * edgeAlpha_0 * mask_0;
            }


            ENDHLSL
        }
    }
}
